### ISSUE TITLE
optout + build failed

### ISSUE THREAD

**Issue by yveslange** [vaadin/vaadin-usage-statistics#37]
Hi, 

While running:

```
npm install --production
npm explore @vaadin/vaadin-usage-statistics -- npm run disable
polymer build
...
[31merror[39m:	Promise rejection: Error: Could not load @vaadin/vaadin-usage-statistics/vaadin-usage-statistics.js (imported by node_modules/%40vaadin/vaadin-element-mixin/vaadin-element-mixin.js): ENOENT: no such file or directory, open '@vaadin/vaadin-usage-statistics/vaadin-usage-statistics.js'
[31merror[39m:	Error: Could not load @vaadin/vaadin-usage-statistics/vaadin-usage-statistics.js (imported by node_modules/%40vaadin/vaadin-element-mixin/vaadin-element-mixin.js): ENOENT: no such file or directory, open '@vaadin/vaadin-usage-statistics/vaadin-usage-statistics.js'
```

If I enable the stats again, the build works

**Comment by Artur-** [comment]
`npm run disable` should rename `vaadin-usage-statistics.js` to `vaadin-usage-statistics.js.bak` and then `vaadin-usage-statistics-optout.js` to `vaadin-usage-statistics.js`. Sounds like thins goes wrong somehow. Check what is in `node_modules/@vaadin/vaadin-usage-statistics` after running `npm run disable`

**Comment by ankon** [comment]
Having the same issue, and did a bit of digging. Basically what seems to happen is this, assuming that `node_modules` doesn't exist in the beginning, and `.npmrc` contains settings for opting out.

1. @vaadin/vaadin-usage-statistics is installed, and runs `postinstall` (check.js)
2. check.js finds that collection is disabled, and renames `vaadin-usage-statistics.js` to `vaadin-usage-statistics.js.bak`, and then `vaadin-usage-statistics-optout.js` to `vaadin-usage-statistics.js`
3. "something" happens that runs @vaadin/vaadin-usage-statistics `postinstall` (check.js) again
4. check.js finds that collection is disabled, and renames `vaadin-usage-statistics.js` to `vaadin-usage-statistics.js.bak` ... *and then fails to rename `vaadin-usage-statistics-optout.js`, because it doesn't exist anymore since step 2*.

At this point the only thing you can do is remove `node_modules/@vaadin/vaadin-usage-statistics` and run `npm install` again.

IMHO this is a bug in @vaadin/vaadin-usage-statistics, it shouldn't _rename_ the source files, but rather have a version for optin and optout, and copy the correct one onto the bare name.

**Comment by ankon** [comment]
Looked further through our build logs, and found the "something": We run `npm rebuild --update-binary` whenever the NodeJS version changes to force updates to certain dependencies with native libraries, and that one does trigger a postinstall for everything.
